=== Perlmint/perlmint.github.com/src/assets/resume/experiences/experience.json
{
    "$schema": "http://json-schema.org/draft-04/schema",
    "title": "Experience",
    "type": "object",
    "required": [
        "title",
        "company",
        "duration",
        "projects"
    ],
    "properties": {
        "title": {
            "type": "string"
        },
        "company": {
            "type": "string"
        },
        "duration": {
            "type": "object",
            "required": [
                "start"
            ],
            "properties": {
                "start": {
                    "type": "string"
                },
                "end": {
                    "type": "string"
                }
            }
        },
        "projects": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/project"
            }
        },
        "next": {
            "type": "string"
        }
    },
    "definitions": {
        "project": {
            "type": "object",
            "required": [
                "id",
                "name",
                "tags"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    }
}

=== Perlmint/perlmint.github.com/src/assets/resume/experiences/0003.json
{
    "$schema": "./experience.json",
    "company": "넥스트플로어",
    "duration": {
        "start": "2017-02-01 00:00:00 GMT+09"
    },
    "projects": [
        {
            "id": "nextfloor-01",
            "name": "드래곤플라이트 미니",
            "tags": [
                "Typescript",
                "Webpack",
                "HTML5",
                "WebGL"
            ]
        }
    ],
    "title": "소프트웨어 개발자"
}

=== Perlmint/perlmint.github.com/src/assets/resume/experiences/0002.json
{
    "$schema": "./experience.json",
    "company": "모빌팩토리",
    "duration": {
        "end": "2015-07-01 24:00:00 GMT+09",
        "start": "2014-04-02 00:00:00 GMT+09"
    },
    "next": "0003.json",
    "projects": [
        {
            "id": "mobilfactory-01",
            "name": "三国飞天",
            "tags": [
                "cpp",
                "csharp",
                "Thrift",
                "Boost"
            ]
        }
    ],
    "title": "소프트웨어 개발자"
}

=== Perlmint/perlmint.github.com/src/assets/resume/experiences/0001.json
{
    "$schema": "./experience.json",
    "company": "사이냅소프트",
    "duration": {
        "end": "2014-04-01 24:00:00 GMT+09",
        "start": "2012-08-01 00:00:00 GMT+09"
    },
    "next": "0002.json",
    "projects": [
        {
            "id": "synap-01",
            "name": "HTML 변환기 2013",
            "tags": [
                "cpp",
                "Javascript",
                "HTML5",
                "CMake"
            ]
        },
        {
            "id": "synap-02",
            "name": "모바일 오피스 (네이버 모바일 오피스)",
            "tags": [
                "cpp",
                "Protobuf",
                "CMake"
            ]
        }
    ],
    "title": "소프트웨어 개발자"
}
